pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ashask2781/course-jenkins-project'
                sh 'ls -ltr'
            }
        }

        stage('Setup') {
            steps {
                sh "pip install -r requirements.txt"          
            }
        }
        stage('Test') {
            steps {
                sh "pytest"
                
            }
        }      
    }
}
